version: '3'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: mibasededatos
      POSTGRES_USER: usuario
      POSTGRES_PASSWORD: contraseña
    volumes:
      - ./db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
