version: '3'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: portfolio_db
      POSTGRES_USER: androidev
      POSTGRES_PASSWORD: aoie420ndrdv
    volumes:
      - ./db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
